# Generated by Django 6.0.8 on 2026-08-31 04:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_live', models.BooleanField(db_index=True, default=True)),
                ('sort', models.PositiveIntegerField(default=100, help_text='Low numbers first.')),
                ('year', models.CharField(blank=True, max_length=16)),
                ('title', models.CharField(max_length=140)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('confirmed', models.BooleanField(default=False, help_text='Only confirmed milestones are printed on the site.')),
            ],
            options={
                'ordering': ('sort', '-year'),
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kicker', models.CharField(default='Create · Build · Train', max_length=120)),
                ('headline', models.CharField(default='One house. Three rooms.', max_length=200)),
                ('lead', models.TextField(default='Paul Frendach. Maryland. Films, interfaces, and sessions made by one pair of hands.')),
                ('contact_email', models.EmailField(default='hello@paulfrendach.com', max_length=254)),
                ('location', models.CharField(default='Maryland', max_length=120)),
                ('footer_line', models.CharField(default='Love the process.', max_length=200)),
                ('booking_note', models.CharField(blank=True, default='Small roster. High school first. Few clients, full attention.', max_length=200)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('show_intro_sting', models.BooleanField(default=True, help_text='Play the 10s sting in the home hero.')),
            ],
            options={
                'verbose_name': 'site configuration',
                'verbose_name_plural': 'site configuration',
            },
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_live', models.BooleanField(db_index=True, default=True)),
                ('sort', models.PositiveIntegerField(default=100, help_text='Low numbers first.')),
                ('slug', models.SlugField(choices=[('create', 'Create — Vision Oasis'), ('build', 'Build — Web'), ('train', 'Train — FRENDACH')], max_length=16, unique=True)),
                ('name', models.CharField(help_text='Vision Oasis / Web / FRENDACH', max_length=60)),
                ('verb', models.CharField(help_text='Create / Build / Train', max_length=20)),
                ('descriptor', models.CharField(help_text='Content & Cinema, Soccer Training…', max_length=80)),
                ('kicker', models.CharField(blank=True, max_length=120)),
                ('headline', models.CharField(max_length=200)),
                ('lead', models.TextField()),
                ('card_line', models.CharField(help_text='One line on the home page card.', max_length=160)),
                ('cta_label', models.CharField(default='Enter', max_length=40)),
                ('hero_image', models.ImageField(blank=True, upload_to='worlds/')),
            ],
            options={
                'ordering': ('sort', 'slug'),
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField()),
                ('budget', models.PositiveIntegerField(blank=True, help_text='Optional, in whole dollars.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=10)),
                ('source_path', models.CharField(blank=True, max_length=200)),
                ('world', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='house.world')),
            ],
            options={
                'verbose_name_plural': 'inquiries',
                'ordering': ('-created_at',),
            },
        ),
    ]
