# Generated by Django 6.0.8 on 2026-08-31 04:26

import apps.train.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_live', models.BooleanField(db_index=True, default=True)),
                ('sort', models.PositiveIntegerField(default=100, help_text='Low numbers first.')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=60)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_live', models.BooleanField(db_index=True, default=True)),
                ('sort', models.PositiveIntegerField(default=100, help_text='Low numbers first.')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('format', models.CharField(choices=[('1v1', 'One to one'), ('group', 'Small group'), ('film', 'Film session'), ('block', 'Multi-week block')], default='1v1', max_length=10)),
                ('summary', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('focus', models.TextField(blank=True, help_text='One bullet per line. What the session actually works on.')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('capacity', models.PositiveSmallIntegerField(default=1, help_text='Players per slot.', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to show the price note instead.', max_digits=7, null=True)),
                ('price_note', models.CharField(blank=True, default='On request', max_length=80)),
                ('requires_film', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('sort', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('location', models.CharField(default='Southern Maryland', max_length=120)),
                ('capacity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('open', 'Open'), ('held', 'Held'), ('closed', 'Closed')], default='open', max_length=8)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('session_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='train.sessiontype')),
            ],
            options={
                'ordering': ('starts_at',),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=apps.train.models.booking_reference, editable=False, max_length=12, unique=True)),
                ('player_name', models.CharField(max_length=120)),
                ('player_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('club_or_school', models.CharField(blank=True, max_length=120)),
                ('position', models.CharField(blank=True, max_length=60)),
                ('contact_name', models.CharField(blank=True, help_text='Parent or guardian, if the player is a minor.', max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('goal', models.TextField(blank=True, help_text='What they want out of the session.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='pending', max_length=10)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('internal_note', models.TextField(blank=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='train.slot')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('session_type', 'starts_at'), name='unique_slot_per_session_start'),
        ),
    ]
