# Generated by Django 6.0.8 on 2026-08-31 04:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_live', models.BooleanField(db_index=True, default=True)),
                ('sort', models.PositiveIntegerField(default=100, help_text='Low numbers first.')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('summary', models.CharField(max_length=200)),
                ('deliverables', models.TextField(help_text='One deliverable per line.')),
                ('turnaround', models.CharField(blank=True, default='2 weeks', max_length=60)),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_note', models.CharField(blank=True, default='On request', max_length=80)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('sort', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_live', models.BooleanField(db_index=True, default=True)),
                ('sort', models.PositiveIntegerField(default=100, help_text='Low numbers first.')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('kind', models.CharField(choices=[('film', 'Film'), ('reel', 'Reel'), ('stills', 'Stills'), ('session', 'Session film')], default='film', max_length=10)),
                ('year', models.CharField(blank=True, max_length=8)),
                ('client', models.CharField(blank=True, max_length=120)),
                ('blurb', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('poster', models.ImageField(blank=True, upload_to='create/posters/')),
                ('video_url', models.URLField(blank=True, help_text='Vimeo / YouTube embed or file URL.')),
                ('runtime', models.CharField(blank=True, help_text='e.g. 1:42', max_length=20)),
                ('credit', models.CharField(default='Vision Oasis', max_length=120)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'work',
                'ordering': ('sort', '-year', 'title'),
            },
        ),
    ]
