# Generated by Django 6.0.8 on 2026-08-31 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_live', models.BooleanField(db_index=True, default=True)),
                ('sort', models.PositiveIntegerField(default=100, help_text='Low numbers first.')),
                ('name', models.CharField(max_length=80)),
                ('kicker', models.CharField(blank=True, help_text='e.g. 01 / Pre', max_length=40)),
                ('blurb', models.CharField(max_length=220)),
                ('detail', models.TextField(blank=True)),
                ('gear', models.CharField(blank=True, help_text='Comma separated. What it is shot on.', max_length=160)),
            ],
            options={
                'ordering': ('sort', 'name'),
            },
        ),
        migrations.AddField(
            model_name='work',
            name='aspect',
            field=models.CharField(choices=[('wide', '2.39:1'), ('video', '16:9'), ('tall', '4:5'), ('square', '1:1')], default='wide', max_length=8),
        ),
        migrations.AddField(
            model_name='work',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Public Instagram post or reel URL. Embedded on the work page.'),
        ),
    ]
